[workspace]
resolver = "2"
members = ["parserule", "rsepitran", "mixtec_fst"]

# Specify a consistent version of rustfst for all crates
[workspace.dependencies]
rustfst = "1.1.6" # Use the newer version
anyhow = "1.0.98"
unicode-normalization = "0.1"
